### ISSUE TITLE
Build as part of daily-grunt-work?

### ISSUE THREAD

**Issue by zepumph** [phetsims/skiffle#2]
I learned about this incredibly cool tool in a demo today. Nice job @jbphet et al. We have a script that runs every night (https://github.com/phetsims/perennial/blob/master/bin/daily-grunt-work.sh).  Want to add this to that file too so that it builds automatically? 

If you agree with this, just commit this and it will get picked up, but when I built skiffle locally it had changes, so I don't want to commit this until talking with @jbphet.

```diff
Index: bin/daily-grunt-work.sh
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/bin/daily-grunt-work.sh b/bin/daily-grunt-work.sh
--- a/bin/daily-grunt-work.sh	(revision f46b3f4691e4ab8264db3d73c1a395414da2e863)
+++ b/bin/daily-grunt-work.sh	(date 1670962202665)
@@ -83,6 +83,15 @@
 git push
 cd ..
 
+##########################################################################################################
+
+echo "BUILD SKIFFLE:"
+cd skiffle || exit
+grunt
+git commit -am "Update skiffle build from daily grunt work" --no-verify
+git push
+cd ..
+
 ##########################################################################################################
 ##########################################################################################################
 ##########################################################################################################
```

**Comment by jbphet** [comment]
Thanks @zepumph.  I manually updated the soundboard, then added the patch above.  Hopefully it will stay up to date automatically from now on.  I'll close this issue, but will keep an eye out for any problems with the rebuild process.
